name: train
description: train code

inputs:
- {name: code_uri,    type: String, description: 'GCS URI of src.tar.gz'}
- {name: output_path, type: String, description: 'GCS output path'}

implementation:
  container:
    image: IMAGE
    command:
      - python3
      - entrypoint.py
      - --code_uri
      - {inputValue: code_uri}
      - --output_path
      - {inputValue: output_path}
